/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.MessageDAO;
import ENTITIES.Message;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Becem
 */
public class InboxGUI extends javax.swing.JFrame {
 private final Inbox modele = new Inbox();
    /**
     * Creates new form InboxGUI
     */
    public InboxGUI() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
      jTable1.setAutoCreateRowSorter(true);
        
        Color c = new Color(63,70,73);
        TableRowSorter<TableModel> sorter = new TableRowSorter<>(jTable1.getModel());
        jScrollPane1.setBorder(null);
        jTable1.setRowSorter(sorter);
        jTable1.setFillsViewportHeight(true);
        jTable1.setShowHorizontalLines(false);
        jTable1.setShowVerticalLines(true);
        JTableHeader header = jTable1.getTableHeader();
        Color bgcolor = new Color(45,47,49);
        Color focolor = new Color(244,244,244);
        header.setBackground(bgcolor);
        header.setForeground(focolor);
        header.setBorder(null);
        
        
         getContentPane().setBackground(c); 
          DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
            renderer.setHorizontalAlignment(SwingConstants.CENTER);
            TableColumn AlignementCol;
            for(int i = 0; i < modele.getColumnCount(); i++)
            {
                AlignementCol= jTable1.getColumnModel().getColumn(i);
                AlignementCol.setCellRenderer(renderer);
            } 
            
             for(int i = 0; i < modele.getColumnCount(); i++)
            {
                TableColumn column = jTable1.getColumnModel().getColumn(i);
                column.setHeaderRenderer(new CustomCellRender());
            }
        //end set header border:disabled
        Color HeaderColorBackground = new Color(34,168,108);
        header.setBackground(HeaderColorBackground);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        New_msg_but = new javax.swing.JLabel();
        MenuInbox = new javax.swing.JLabel();
        DeleteMsg = new javax.swing.JLabel();
        jMsgS = new javax.swing.JButton();
        jMsgR = new javax.swing.JButton();
        MenuInboxBut = new javax.swing.JLabel();
        MenuUsersBut = new javax.swing.JLabel();
        MenuAdvertBut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(63, 70, 73));
        setForeground(java.awt.Color.black);
        setMinimumSize(new java.awt.Dimension(0, 600));
        setPreferredSize(new java.awt.Dimension(1040, 506));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 0, 0));
        jScrollPane1.setBorder(null);

        jTable1.setBackground(new java.awt.Color(46, 60, 50));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 204, 204));
        jTable1.setModel(modele);
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTable1.setGridColor(new java.awt.Color(63, 71, 73));
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTable1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 870, 352));

        New_msg_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_new_msg_init.png"))); // NOI18N
        New_msg_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                New_msg_butMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                New_msg_butMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                New_msg_butMouseExited(evt);
            }
        });
        getContentPane().add(New_msg_but, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 157, -1, -1));

        MenuInbox.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Menu_admin_Inbox.png"))); // NOI18N
        MenuInbox.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(MenuInbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 1100, -1));

        DeleteMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_Delete_msg_Out.png"))); // NOI18N
        DeleteMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DeleteMsgMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DeleteMsgMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DeleteMsgMouseExited(evt);
            }
        });
        getContentPane().add(DeleteMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 205, -1, -1));

        jMsgS.setText("Message Sent");
        jMsgS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsgSActionPerformed(evt);
            }
        });
        getContentPane().add(jMsgS, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 273, -1, -1));

        jMsgR.setText("Message Recieved");
        jMsgR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMsgRActionPerformed(evt);
            }
        });
        getContentPane().add(jMsgR, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        MenuInboxBut.setText("jLabel4");
        MenuInboxBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuInboxBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuInboxButMouseClicked(evt);
            }
        });
        getContentPane().add(MenuInboxBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 100, 60));

        MenuUsersBut.setText("jLabel1");
        MenuUsersBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuUsersBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuUsersButMouseClicked(evt);
            }
        });
        getContentPane().add(MenuUsersBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 120, 60));

        MenuAdvertBut.setText("jLabel1");
        MenuAdvertBut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        MenuAdvertBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuAdvertButMouseClicked(evt);
            }
        });
        getContentPane().add(MenuAdvertBut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 100, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void New_msg_butMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_msg_butMouseEntered
      New_msg_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_new_msg_click.png")));
    }//GEN-LAST:event_New_msg_butMouseEntered

    private void New_msg_butMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_msg_butMouseExited
        New_msg_but.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_new_msg_init.png")));
    }//GEN-LAST:event_New_msg_butMouseExited

    private void New_msg_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_New_msg_butMouseClicked
        SendMsg SM = new SendMsg();
       SM.show();
    }//GEN-LAST:event_New_msg_butMouseClicked

    private void DeleteMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMsgMouseClicked
       int[] selection = jTable1.getSelectedRows();
        for(int i = selection.length - 1; i >= 0; i--)
        {
            modele.remove_Message(selection[i]);
        }
    }//GEN-LAST:event_DeleteMsgMouseClicked

    private void DeleteMsgMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMsgMouseEntered
         DeleteMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_Delete_msg_In.png")));
    }//GEN-LAST:event_DeleteMsgMouseEntered

    private void DeleteMsgMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DeleteMsgMouseExited
       DeleteMsg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Button_Delete_msg_Out.png")));
    }//GEN-LAST:event_DeleteMsgMouseExited

    private void jMsgSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsgSActionPerformed
       modele.ShowAllSent();
    }//GEN-LAST:event_jMsgSActionPerformed

    private void jMsgRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMsgRActionPerformed
        modele.ShowAllRecieved();
    }//GEN-LAST:event_jMsgRActionPerformed

    private void MenuAdvertButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuAdvertButMouseClicked
       RoadList a = new RoadList();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuAdvertButMouseClicked

    private void MenuUsersButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuUsersButMouseClicked
        AffichageUserGui a = new AffichageUserGui();
        a.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_MenuUsersButMouseClicked

    private void MenuInboxButMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuInboxButMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuInboxButMouseClicked
                                                
                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InboxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InboxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InboxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InboxGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                
                new InboxGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeleteMsg;
    private javax.swing.JLabel MenuAdvertBut;
    private javax.swing.JLabel MenuInbox;
    private javax.swing.JLabel MenuInboxBut;
    private javax.swing.JLabel MenuUsersBut;
    private javax.swing.JLabel New_msg_but;
    private javax.swing.JButton jMsgR;
    private javax.swing.JButton jMsgS;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
