/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import DAO.MessageDAO;
import ENTITIES.Message;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author user
 */
public class MessageGUI extends javax.swing.JFrame {

    /**
     * Creates new form MessageGUI
     */
    public MessageGUI() {
        initComponents();
         Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
    }
    
    public MessageGUI(int id) {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        //instancier message
        Message M = new Message();
        //instancier dao
        MessageDAO MD = new MessageDAO();
        //appeler la methode (get message by id) --> message
        M =MD.findUserByLogin(id);
        
        //ajouti lil label ex : label.setText(message.getFrom());
        Sender.setText(M.getFrom());
        Reciever.setText(M.getTo());
        Jmsg.setText(M.getContent());
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sender = new javax.swing.JLabel();
        To_lab = new javax.swing.JLabel();
        From_lab = new javax.swing.JLabel();
        Reciever = new javax.swing.JLabel();
        Message = new javax.swing.JLabel();
        Date = new javax.swing.JLabel();
        Reply = new javax.swing.JButton();
        Cancel = new javax.swing.JLabel();
        Jmsg = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(63, 70, 73));
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sender.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Sender.setForeground(new java.awt.Color(225, 225, 225));
        getContentPane().add(Sender, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 90, 30));

        To_lab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        To_lab.setForeground(new java.awt.Color(33, 154, 101));
        To_lab.setText("To");
        getContentPane().add(To_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, -1, -1));

        From_lab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        From_lab.setForeground(new java.awt.Color(33, 154, 101));
        From_lab.setText("From");
        getContentPane().add(From_lab, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, -1, -1));

        Reciever.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Reciever.setForeground(new java.awt.Color(225, 225, 225));
        getContentPane().add(Reciever, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 115, 80, 20));

        Message.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Message.setForeground(new java.awt.Color(225, 225, 225));
        getContentPane().add(Message, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 356, 126));

        Date.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        Date.setForeground(new java.awt.Color(225, 225, 225));
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 20, 10));

        Reply.setText("Reply");
        getContentPane().add(Reply, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, -1, -1));

        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Cancel_Out.png"))); // NOI18N
        Cancel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CancelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CancelMouseExited(evt);
            }
        });
        getContentPane().add(Cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 607, -1, -1));

        Jmsg.setBackground(new java.awt.Color(233, 246, 241));
        Jmsg.setColumns(20);
        Jmsg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Jmsg.setForeground(new java.awt.Color(125, 125, 125));
        Jmsg.setRows(5);
        Jmsg.setBorder(null);
        getContentPane().add(Jmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 290, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Cadre_Blanc.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, -1));

        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Message_View_1.png"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Message msg = new Message();
        MessageDAO Msg =new MessageDAO();
       msg= Msg.ViewMessage(31);
        System.out.println(msg.getFrom());
        
        Sender.setText(msg.getFrom());
        Reciever.setText(msg.getTo());
        Message.setText(msg.getContent());
        
    }//GEN-LAST:event_formWindowOpened

    private void CancelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseExited
      Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Cancel_Out.png")));
    }//GEN-LAST:event_CancelMouseExited

    private void CancelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseEntered
        Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/Buttons/Cancel.png")));
    }//GEN-LAST:event_CancelMouseEntered

    private void CancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelMouseClicked
       this.dispose();
    }//GEN-LAST:event_CancelMouseClicked

     
                                  

                              
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MessageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MessageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MessageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MessageGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MessageGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JLabel Cancel;
    private javax.swing.JLabel Date;
    private javax.swing.JLabel From_lab;
    private javax.swing.JTextArea Jmsg;
    private javax.swing.JLabel Message;
    private javax.swing.JLabel Reciever;
    private javax.swing.JButton Reply;
    private javax.swing.JLabel Sender;
    private javax.swing.JLabel To_lab;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
