/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI;

import ENTITIES.User;

/**
 *
 * @author Rissen
 */
public class ProfilClient extends javax.swing.JFrame {

    /**
     * Creates new form ProfilClient
     */
    public ProfilClient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Sex = new javax.swing.JTextField();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        Date = new javax.swing.JTextField();
        Login = new javax.swing.JTextField();
        add = new javax.swing.JButton();
        Find = new javax.swing.JButton();
        Photo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Sex.setEditable(false);
        Sex.setBackground(new java.awt.Color(45, 47, 49));
        Sex.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        Sex.setForeground(new java.awt.Color(34, 168, 108));
        Sex.setBorder(null);
        getContentPane().add(Sex, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 120, 30));

        FirstName.setEditable(false);
        FirstName.setBackground(new java.awt.Color(45, 47, 49));
        FirstName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(34, 168, 108));
        FirstName.setBorder(null);
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 120, 30));

        LastName.setEditable(false);
        LastName.setBackground(new java.awt.Color(45, 47, 49));
        LastName.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(34, 168, 108));
        LastName.setBorder(null);
        getContentPane().add(LastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 120, 30));

        Address.setEditable(false);
        Address.setBackground(new java.awt.Color(45, 47, 49));
        Address.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(34, 168, 108));
        Address.setBorder(null);
        getContentPane().add(Address, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 190, 120, 30));

        City.setEditable(false);
        City.setBackground(new java.awt.Color(45, 47, 49));
        City.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        City.setForeground(new java.awt.Color(34, 168, 108));
        City.setBorder(null);
        getContentPane().add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 120, 30));

        Date.setEditable(false);
        Date.setBackground(new java.awt.Color(45, 47, 49));
        Date.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        Date.setForeground(new java.awt.Color(34, 168, 108));
        Date.setBorder(null);
        getContentPane().add(Date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 120, 30));

        Login.setEditable(false);
        Login.setBackground(new java.awt.Color(45, 47, 49));
        Login.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        Login.setForeground(new java.awt.Color(34, 168, 108));
        Login.setBorder(null);
        Login.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 10, 130, 30));

        add.setBackground(new java.awt.Color(34, 168, 108));
        add.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        add.setForeground(new java.awt.Color(45, 47, 49));
        add.setText("ADD ROAD");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        getContentPane().add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 140, 130, 50));

        Find.setBackground(new java.awt.Color(34, 168, 108));
        Find.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        Find.setForeground(new java.awt.Color(45, 47, 49));
        Find.setText("FIND ROAD");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        getContentPane().add(Find, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, -1, 50));

        Photo.setBackground(new java.awt.Color(45, 47, 49));
        Photo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/ProfilClient.png"))); // NOI18N
        getContentPane().add(Photo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        User user = new User();
        ProfilClientCode profile = new ProfilClientCode();
       // user = profile.getUser();
        Login.setText(AuthClient.clients.getLogin());
        FirstName.setText(AuthClient.clients.getFirstName());
        LastName.setText(AuthClient.clients.getLastName());
        Address.setText(AuthClient.clients.getAddress());
        City.setText(AuthClient.clients.getCity());
        Date.setText(AuthClient.clients.getDateB().toString());
        Sex.setText(AuthClient.clients.getSexe());
        

    
        
    
    }//GEN-LAST:event_formWindowOpened

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        AddCarRoad addroad=new AddCarRoad();
        addroad.setVisible(rootPaneCheckingEnabled);
        this.dispose();
       
    }//GEN-LAST:event_addActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        RoadList findroad = new RoadList();
        findroad.setVisible(rootPaneCheckingEnabled);
        this.dispose();
    }//GEN-LAST:event_FindActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProfilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProfilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProfilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProfilClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProfilClient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField City;
    private javax.swing.JTextField Date;
    private javax.swing.JButton Find;
    private javax.swing.JTextField FirstName;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField Login;
    private javax.swing.JLabel Photo;
    private javax.swing.JTextField Sex;
    private javax.swing.JButton add;
    // End of variables declaration//GEN-END:variables
}
